### PR TITLE
Allow setting logger propagation in config!

### PR DESCRIPTION
**Pull request by iamed2**

### CODE REVIEW

**Comment by rofinn** [comment]
1) `config!` is starting to have too many keyword args.
2) I think needing to explicitly create a logger or use `setpropagating!` is appropriate if you actively want to avoid propagation up the hierarchy.
3) It would have been nice if someone reviewed this before it was merged.

**Comment by iamed2** [comment]
1. Python's logging module considers `propagate` important enough to have in its config functions

2. If you want to make a logger that handles custom record types with a custom formatter, it's annoying to have to add the call to `setpropagating!` to prevent the root logger from erroring on display.

screenshot 2018-08-07 07 15 08

3. It hasn't been tagged, we can revert it. But I don't think we should.

**Comment by rofinn** [comment]
> Python's logging module considers propagate important enough to have in its config functions

Ahh, okay. `Memento.config!` was designed after [`basicConfig`](https://docs.python.org/2/library/logging.html?highlight=basicconfig#logging.basicConfig) which doesn't take a `propagate` keyword. I'm guessing you were thinking of [`dictConfig`](https://docs.python.org/2/library/logging.config.html?highlight=propagate#configuration-functions)? I guess it doesn't really make sense to distinguish the two in julia as we could just dispatch on an `Associative` in the future.

**Comment by iamed2** [comment]
Ah yes. I _think_ fileConfig also allows this, although I couldn't find a specific example of that. 

I think the difference is that `basicConfig` only operates on the root logger, whereas `dictConfig` and `fileConfig` can set properties on any logger.

**Pull request merged**
